### ISSUE TITLE
sounddevice.PortAudioError: Error querying device -1

### ISSUE THREAD

**Issue by JyunYiWu-0218** [tr1pzz/Realtime_PyAudio_FFT#27]
Following the README.md operation will run out of this error: 
Traceback (most recent call last):
  File "/home/junyiwu/Realtime_PyAudio_FFT/Realtime_PyAudio_FFT/run_FFT_analyzer.py", line 4, in <module>
    ear = Stream_Analyzer(
  File "/home/junyiwu/Realtime_PyAudio_FFT/Realtime_PyAudio_FFT/src/stream_analyzer.py", line 51, in __init__
    self.stream_reader = Stream_Reader(
  File "/home/junyiwu/Realtime_PyAudio_FFT/Realtime_PyAudio_FFT/src/stream_reader_sounddevice.py", line 52, in __init__
    with sd.InputStream(samplerate=self.rate,
  File "/home/junyiwu/.local/lib/python3.10/site-packages/sounddevice.py", line 1381, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/home/junyiwu/.local/lib/python3.10/site-packages/sounddevice.py", line 777, in __init__
    _get_stream_parameters(kind, device, channels, dtype, latency,
  File "/home/junyiwu/.local/lib/python3.10/site-packages/sounddevice.py", line 2571, in _get_stream_parameters
    info = query_devices(device)
  File "/home/junyiwu/.local/lib/python3.10/site-packages/sounddevice.py", line 569, in query_devices
    raise PortAudioError('Error querying device {0}'.format(device))

want to know how to improve
Ubuntu 22.04.1

**Comment by Flying3voveU** [comment]
I had the same problem. But at the top of the terminal, it was saying that "No working microphone devices found!". So I checked my microphone settings and I found that I had no microphone enabled. I enabled Realtek(R) Audio in microphone section then it worked!
